/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.1.1/samples
 */

defaultTasks("clean", "run")

tasks.register("clean"){
    doLast{
        println("Cleaning previous build")
    }   
}

tasks.register("run"){
    doLast{
        println("Running output from build")
    }   
}

tasks.register("deploy"){
    doLast{
        println("Deploying artefacts to production")
    }   
}

tasks.register("hello"){
    doLast{
        println("Hello!")
    }   
}
tasks.register("greetings"){
    dependsOn("hello")
    doLast{
        println("from gradle")
    }   
}